### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by wengcanbin1** [LebronAl/MIT6.824-2021#10]
大佬可以给出完整代码吗？邮箱759176663@qq.com
感谢

**Comment by OneSizeFitsQuorum** [comment]
已悄悄放到另一个分支了，希望还是尽量自己完成吧~

**Comment by DayChan** [comment]
> 已悄悄放到另一个分支了，希望还是尽量自己完成吧~

大佬放在哪个分支了呀🙏

**Comment by DayChan** [comment]
在别人的fork里面找到啦，感谢🙏
