### ISSUE TITLE
关于 lab4B 中的分片迁移模式的讨论(push/pull)

### ISSUE THREAD

**Issue by SwordHarry** [LebronAl/MIT6.824-2021#11]
博主你好，对于lab4B 中的代码实现， `GetShardsData `  的实现中，博主做了 configNum 检查之后，就直接返回分片数据了；这里是不是需要主动调用一次 raft.Start 来确保 group 是正常的？
这里我提个我自己的理解，不知道是否有误，考虑一个 group 内 5 个 server 出现分区的情况：
导致 [oldLeader, server] [newLeader, server, server]，在一个 configNum 周期内， newLeader 和客户端通讯并跟新了自己的数据，然后同时也存在分片迁移，另一个 group 将 pulling 发送给了 oldLeader，oldLeader 直接返回旧的分片数据了，这是否有可能发生？

======================= 分割线 ===================
然后这边想和你讨论一下 push 和 pull 的实现，我这里一开始尝试实现 push，但是发现不太好搞QAQ
对于分片迁移的 push 和 pull 模式，我有思考过一点，但是感觉还是有一点不同
考虑 push 模式和 pull 模式的不同：

如果是 push 模式，存在 G1 和 G2，G1 需要 push 分片数据给 G2，push 成功后需要 GC，即：
G1 ===== push args ======> G2
G2 Start -> apply
G1 <==== push reply ======= G2
一次 rpc 即可知道 push 成功了，随即 G1 即可进行 GC
G1 Start GC -> apply

如果是 pull 模式，G1 需要从G2 pull 分片数据，pull 成功后，G2 需要 GC，即：
G1 ===== pull args ======> G2
G2 Start -> apply（这里我看博主的代码是没有这一步的）
G1 <===== pull reply ====== G2
G1 Start -> apply
G2 并不能明确 pull reply 是否真正到达，只有 G1 才可以明确，所以需要 G1 重试，G2 接收到后方可GC
G1 ===== GC args =====> G2
G2 Start GC -> apply
G1 <===== GC reply ===== G2

初步猜想，各有利弊，push 模式比 pull 模式少一次 rpc 调用
但经过故障考虑，还是使用 pull 模式更佳，考虑这样的一个情况：
若使用 pushing 模式，一个 group 故障后重启，则 configNum 可能会从 低版本 开始，此时它会以落后的 configNum push 数据给其他 group，
其他 group 检测到落后 configNum 的 push，可以直接返回 OK 即可，但是其落后的 group 将永远拿不到需要从其他 group pulling 的数据，因为是 push 模式，需要其他 group 主动推，但是其他 group 已经是最新的 configNum；
所以这种实现 push 模式会实现不了，这个考虑对吗？

**Comment by LebronAl** [comment]
> 导致 [oldLeader, server] [newLeader, server, server]，在一个 configNum 周期内， newLeader 和客户端通讯并跟新了自己的数据，然后同时也存在分片迁移，另一个 group 将 pulling 发送给了 oldLeader，oldLeader 直接返回旧的分片数据了，这是否有可能发生？

**Comment by OneSizeFitsQuorum** [comment]
你的问题很深刻哈哈哈，一下子我竟然感觉无法回答。今天我重新看了一下我当时的文档和代码，这里跟你做个回复吧。

> 导致 [oldLeader, server] [newLeader, server, server]，在一个 configNum 周期内， newLeader 和客户端通讯并跟新了自己的数据，然后同时也存在分片迁移，另一个 group 将 pulling 发送给了 oldLeader，oldLeader 直接返回旧的分片数据了，这是否有可能发生？

我的理解是这种情况不会出现。因为一旦这个 raft 组更新了这个 configNum 的 config，其 shard 的 status 应该就是 BePulling，且该 configNum 在被 pull 的 raft group 发 RPC 来 GC 之前都不会变（重启恢复的时候会变，但此时有另外的机制来避免写入的新数据被覆盖）。即使 oldLeader 与 majority 发生了分区，其对应 shard 的数据在这个 configNum 也是最新的，因为新的 leader 不拥有这个 shard 的写权限，会让客户端一直重试的。总体来看，这里是以牺牲 liveness 的代价（shard 迁移时不可读写）来保证绝对的 safety 的。

至于你下面的疑问，我可以做三点陈述吧：
- 如上所述，最开始 pull 那里其实不需要被 pull 的 leader 去 start 来确认自己是不是 leader，因为确认了也没用，你依然无法解决确认是 leader 过后打包状态机的时候产生分区，这个 raft 组选出了新 leader 写了新数据的情况。所以必须给 shard 加入状态牺牲 liveness 才可以解决这个问题。
- 不论是 push 还是 pull，维护 shard 的状态是保证 safety 最重要的一环。建议你再仔细理解下我代码中对 4 种状态的注释和相关的代码判断。比如 config 不全变为 serving 时这个 raft group 就不能去拉新的 config 过来，所以即使是 push 模式，一个正准备 push 的 raft group 挂了，其他 raft group 的 config 如果有 shard 处于 bePushing 状态的话也不能发生更新，那么就不会有你说的这个问题了。
- push 或者 pull，我当时感觉实现难度差不多就实现成了 pull。后面又仔细想了想，其实 pull 的难度要更大一些，push 不仅能够减少一次 rpc，而且实现起来更方便一些。如果你不想踩太多坑的话，建议直接用 push 写吧，应该会更容易一些。

**Comment by SwordHarry** [comment]
👍了解了，目前还在 debug lab4B，感觉还会有很多坑，感谢感谢

**Comment by SwordHarry** [comment]
> 不论是 push 还是 pull，维护 shard 的状态是保证 safety 最重要的一环。建议你再仔细理解下我代码中对 4 种状态的注释和相关的代码判断。比如 config 不全变为 serving 时这个 raft group 就不能去拉新的 config 过来，所以即使是 push 模式，一个正准备 push 的 raft group 挂了，其他 raft group 的 config 如果有 shard 处于 bePushing 状态的话也不能发生更新，那么就不会有你说的这个问题了。

关于这个重放，我还有个疑问....
configNum: []int (index: shardId, value: gid)
1: [100, 100, 100] 
2: [100, 101, 102]
3: [100, 100, 100]
4: [100, 101, 102]
当 gid 为 101 的 group 直接 shutdown 了，然后从 configNum 0 开始重放（如果没有 persister 做快照）
如果是 pull 模式，101 在 conigNum 2 会 pull 100 的1号分片，在 configNum 3 时，101的 1 号分片又一直为 BePulling，等待 100 的 pull ，但是 100 在 configNum 4， 然后 101 就一直卡在 configNum 3 了
如果是 push 模式，在 configNum 2 时，101 的 1 号分片为 BePushing，一直等待 100 的 push，但是 100 和 102 都在 configNum 4 了
这个重放的问题是否会发生？

**Comment by OneSizeFitsQuorum** [comment]
> 如果是 pull 模式，101 在 conigNum 2 会 pull 100 的1号分片，在 configNum 3 时，101的 1 号分片又一直为 BePulling，等待 100 的 pull ，但是 100 在 configNum 4， 然后 101 就一直卡在 configNum 3 了。 

如果 2 号分片成功被节点 1 收到了，节点 1 在没有成功 gc 节点 2 的 2 分片之前都会将该 shard 处于 gc 状态，这个时候节点 2 重不重启都不影响。如果节点 1 成功 gc 了节点 2 的 2 号分片， 那么节点 2 重启应该自己保证可以恢复到 2 号分片状态恢复正常态的状态。
