### ISSUE TITLE
关于lab2Dsnapshot函数的讨论

### ISSUE THREAD

**Issue by boymucheng** [LebronAl/MIT6.824-2021#12]
您好，我在snapshot这一个函数里，碰到了一个错误，不知道您碰到过没，就是snapshot函数里rf.log[index – rf.getFirstEntry().Index:]，偶尔会报错，例如slice[10:8]，一直没查出来原因，而且只是偶尔会有这个错误。

**Comment by OneSizeFitsQuorum** [comment]
没遇到过，感觉要不就是锁有问题有并发 race 问题，要不就是该深拷贝的地方没深拷贝

**Comment by boymucheng** [comment]
确实，感觉是锁的问题，有点难排查，这个重复率太低了，之前弄好就没打log
