### ISSUE TITLE
请教有关Raft paper Figure 8的问题

### ISSUE THREAD

**Issue by Hooollin** [LebronAl/MIT6.824-2021#14]
在Figure 8的阶段c中，S1收到了大多数机器（S2、S3）对index=2，term=2的log的确认，在问题出现之前apply到了上层应用，并且返回给客户。S1在发送包含新的commitIndex的AE之前，发生网络分区，导致S1可以与客户通信，但是无法与peer通信。接着S5重启，到了d阶段，覆盖了S2、S3、S4的index=2处的log。此时有新的主机与新Leader S5通信，使得index=2，term=3的log被提交给上层应用。S1自始至终都没有crash，那么与S1通信的客户收到的对index=2，term=2的操作的响应是不是违反了raft的线性一致性呢？这里一直没有想明白，希望大佬解答。

**Comment by Hooollin** [comment]
S5 could be elected leader (with votes from S2, S3, and S4) and overwrite the entry with its own entry from term 3. Figure 8 描述到S5可以被选举成新的Leader，从安全性验证上看是否存在错误呢？S5可以被选成为新的Leader吗？

**Comment by OneSizeFitsQuorum** [comment]
分享一页我的 PPT 吧。

<img width="912" alt="image" src="https://user-images.githubusercontent.com/32640567/157370025-47fa68ec-8583-4e55-9c35-8cc488b670cf.png">

**Comment by Hooollin** [comment]
啊明白了！我想错了，S1只有在crash过后S5才有可能进入term3，所以我问到的那种情况永远不会发生。多谢啦~
