### ISSUE TITLE
请教有关lab 2A的问题

### ISSUE THREAD

**Issue by Vector6662** [LebronAl/MIT6.824-2021#15]
看了大佬的代码有点疑问：
``` go
func (rf *Raft) BroadcastHeartbeat(isHeartBeat bool) {
	for peer := range rf.peers {
		if peer == rf.me {// ❓
			continue
		}
		if isHeartBeat {
			// need sending at once to maintain leadership
			go rf.replicateOneRound(peer)
		} else {
			// just signal replicator goroutine to send entries in batch
			rf.replicatorCond[peer].Signal()
		}
	}
}
```
该方法是作为leader才会调用，“❓”处我觉得会使得这个leader自己election timeout，确切地说作为leader没有什么办法可以reset这个`ticker`中的election timeout。
然后会有这样的输出：`warning: term changed even though there were no failures`。
是否是我理解有误？多谢指教，感激不尽😄😄😄

**Comment by OneSizeFitsQuorum** [comment]
> 该方法是作为leader才会调用，“❓”处我觉得会使得这个leader自己election timeout，确切地说作为leader没有什么办法可以reset这个ticker中的election timeout。

electionTimer 和  heartbeatTimer 是两个 timer 呀？为什么要在心跳函数里面 reset election 的 timer 呢？

**Comment by Vector6662** [comment]
> > 该方法是作为leader才会调用，“❓”处我觉得会使得这个leader自己election timeout，确切地说作为leader没有什么办法可以reset这个ticker中的election timeout。
> 
> electionTimer 和 heartbeatTimer 是两个 timer 呀？为什么要在心跳函数里面 reset election 的 timer 呢？

抱歉我没有表述清楚。我的意思是作为leader，它的electiontimeout也是会到期的
您的`ticker()`代码中：
```go
case <-rf.electionTimer.C:
    rf.mu.Lock()
    rf.ChangeState(StateCandidate)
    rf.currentTerm += 1
    rf.StartElection()
    rf.electionTimer.Reset(RandomizedElectionTimeout())
    rf.mu.Unlock()
```
当作为**leader**的时候electionTimer到期了，也会进行选举，那么2A的test中会有这样的输出：`warning: term changed even though there were no failures`（`TestInitialElection2A`中44行）

**Comment by Vector6662** [comment]
> > 该方法是作为leader才会调用，“❓”处我觉得会使得这个leader自己election timeout，确切地说作为leader没有什么办法可以reset这个ticker中的election timeout。
> 
> electionTimer 和 heartbeatTimer 是两个 timer 呀？为什么要在心跳函数里面 reset election 的 timer 呢？

抱歉我没有表述清楚。我的意思是作为leader，它的electiontimeout也是会到期的
您的`ticker()`代码中：
```go
case <-rf.electionTimer.C:
    rf.mu.Lock()
    rf.ChangeState(StateCandidate)
    rf.currentTerm += 1
    rf.StartElection()
    rf.electionTimer.Reset(RandomizedElectionTimeout())
    rf.mu.Unlock()
```
当作为**leader**的时候electionTimer到期了，也会进行选举，那么2A的test中会有这样的输出：`warning: term changed even though there were no failures`（`TestInitialElection2A`中44行）

我想了一段时间做了一点修改，只有在非leader的时候才会调用`startElection()`，参考了raft论文中的Figure 4：
``` go
case <-rf.electionTimer.C: // 选举时间超时，则开始选举，这个过程参考Figure 2的"Rules for Servers"
  rf.mu.Lock()
  if Leader != rf.state {
      rf.currentTerm++
      rf.changeState(Candidate)
      rf.startElection()
      //todo 重要修正： https://github.com/OneSizeFitsQuorum/MIT6.824-2021/issues/15
      rf.electionTimer.Reset(ElectionTimeOut())
  }
  rf.mu.Unlock()
```
原因是作为leader进行`BroadcastHeartbeat`时是排除了自己的
``` go
if peer == rf.me {
	continue
}
```
于是leader自己也会election timeout，然后成为candidate。但是Figure 4中并没有Leader直接转换为Candidate的箭头。

还改了一个地方，是您的`startElection()`中的：
```go
if response.VoteGranted {
    grantedVotes += 1
    if grantedVotes > len(rf.peers)/2 {
	    DPrintf("{Node %v} receives majority votes in term %v", rf.me, rf.currentTerm)
	    rf.ChangeState(StateLeader)
	    rf.BroadcastHeartbeat(true)
            rf.heartbeatTimer.Reset(HeartbeatTimeOut()) //❗这是我多加的代码
    }
}
```
多添加的原因是，选举成为Leader之前，ticker中的heartbeat timeout会耗尽，**且不会reset**，这是因为成为leader之前不是leader，于是不会执行`if rf.state == StateLeader:`：
``` go
case <-rf.heartbeatTimer.C:
    rf.mu.Lock()
    if rf.state == StateLeader {
    rf.BroadcastHeartbeat(true)
    rf.heartbeatTimer.Reset(StableHeartbeatTimeout())
    }
    rf.mu.Unlock()
```
于是，在`Make()`中初始化时设置的那个heartbeat timeout之后，就再也不会重channel中收到heartbeat timeout了，即使选举成为leader，**也只会执行一次**`rf.BroadcastHeartbeat(true)`，即选举成功时执行的那次。这也是我添加那行的原因：重新“激活”heartbeat timeout。

**Comment by OneSizeFitsQuorum** [comment]
在成为 leader 之后我会将 electionTimer 停掉的。你是不是只看了我文档中的部分代码。。。
```Go
func (rf *Raft) ChangeState(state NodeState) {
	if rf.state == state {
		return
	}
	DPrintf("{Node %d} changes state from %s to %s in term %d", rf.me, rf.state, state, rf.currentTerm)
	rf.state = state
	switch state {
	case StateFollower:
		rf.heartbeatTimer.Stop()
		rf.electionTimer.Reset(RandomizedElectionTimeout())
	case StateCandidate:
	case StateLeader:
		lastLog := rf.getLastLog()
		for i := 0; i < len(rf.peers); i++ {
			rf.matchIndex[i], rf.nextIndex[i] = 0, lastLog.Index+1
		}
		rf.electionTimer.Stop()
		rf.heartbeatTimer.Reset(StableHeartbeatTimeout())
	}
}
```

**Comment by Vector6662** [comment]
> 在成为 leader 之后我会将 electionTimer 停掉的。你是不是只看了我文档中的部分代码。。。

明白了，谢谢大佬解答😄！确实没有注意到有ChangeState的实现🤣

**Comment by Alan-hunter** [comment]
> 在成为 leader 之后我会将 electionTimer 停掉的。你是不是只看了我文档中的部分代码。。。
> 
> ```go
> func (rf *Raft) ChangeState(state NodeState) {
> 	if rf.state == state {
> 		return
> 	}
> 	DPrintf("{Node %d} changes state from %s to %s in term %d", rf.me, rf.state, state, rf.currentTerm)
> 	rf.state = state
> 	switch state {
> 	case StateFollower:
> 		rf.heartbeatTimer.Stop()
> 		rf.electionTimer.Reset(RandomizedElectionTimeout())
> 	case StateCandidate:
> 	case StateLeader:
> 		lastLog := rf.getLastLog()
> 		for i := 0; i < len(rf.peers); i++ {
> 			rf.matchIndex[i], rf.nextIndex[i] = 0, lastLog.Index+1
> 		}
> 		rf.electionTimer.Stop()
> 		rf.heartbeatTimer.Reset(StableHeartbeatTimeout())
> 	}
> }
> ```

大佬，在成为了 leader 后 调用relectionTImer.Stop，但是在 ticker 中不是又继续执行了 reset 吗？
