### ISSUE TITLE
有关liveness的问题2可能并不存在

### ISSUE THREAD

**Issue by weixiaonan1** [LebronAl/MIT6.824-2021#18]
因为heartbeat也会进行日志的同步，所以我觉得您问题2中描述的liveness的问题并不存在。
在您举得例子中，节点1失效，节点2当选leader(logs 是 [1,2]，commitIndex 和 lastApplied 是 1)，节点3为落后的follower(logs 是 [1]，commitIndex 和 lastApplied 是 1)。此时，leader的nextIndex[3]默认为乐观估计的3，即 leader last log index + 1。在发送heartbeat时，prevLogIndex为2，节点3会及时发现日志不一致，并尽快同步到 [1,2]的状态，随之commitIndex , lastApplied均会得到更新，而不必等到下一次写请求过来才完成日志的同步工作。

**Comment by OneSizeFitsQuorum** [comment]
主要是此时的 leader 节点 2 的 commitIndex 会是 1 而不能更新到 2。所以即使节点 2,3 的日志都到了[1,2] 的状态 commitIndex 都只能是 1，直到有一条当前 term 的日志提交时才能将之前 term 的日志隐示提交。

**Comment by weixiaonan1** [comment]
确实，我忘记了只有 log[N].term == currentTerm的才能提交了，谢谢。
