### ISSUE TITLE
Start()后广播的时机

### ISSUE THREAD

**Issue by Vector6662** [LebronAl/MIT6.824-2021#19]
请问您的实现中，当raft被调用`Start()`后，将这条entry同步的时机时什么时候呢？是立即广播还是等到下一次心跳呢？
我目前遇到的问题是在Lab 3A的TestSpeed3A，会超时，我改成了每次都立即广播，虽然效果很好但发送的rpc太多。
我觉得应该是和我设置的心跳超时时间有关系，如果设置得很短比如15ms，就不会出现这个问题

**Comment by OneSizeFitsQuorum** [comment]
下一次心跳或者同步线程刚好执行完开始下一轮吧，最长的延时应该是一轮心跳的时间

**Comment by Vector6662** [comment]
get，谢谢！
