### ISSUE TITLE
关于Lab3的性能问题

### ISSUE THREAD

**Issue by endless-hu** [LebronAl/MIT6.824-2021#22]
Lab3中有一个`SpeedTest`，要求每轮heartbeat至少要执行三条命令，请问你是如何做到的？

即使假设网络通讯**可靠无延迟**，如果只有**一个**客户端**串行**执行命令的话，每轮heartbeat最多只能执行**一条**命令。

我一开始使用的就是简单的串行客户端，需要100s才能完成`SpeedTest`，显然是远远不能满足性能要求。当然我尝试过用异步或缓存来提高性能，但是总会造成线性化测试的失败。

`SpeedTest`测试流程的伪代码如下：

```go
var ck1, ck2 Clerk
v := ck1.Get("0")  // 这个应该是用来发现并保存leader的

begin := time.Now()
for i := 0; i < 1000; i++ {
    ck1.Append("0", " " + i)
}
dur := time.Since(begin)  // 每轮heartbeat相隔100ms，若每轮执行3条指令，1000条指令应在34s内完成

v = ck2.Get("0")  // 线性化要求这条命令应得到 " 0 1 2 3 4 ... 999"
```

**Comment by weixiaonan1** [comment]
可以看博主lab2中复制模型的描述。如果简单实现(不考虑资源浪费)的话，每次上次服务调用Start()时leader都会向peers发送sendAppendEntries()进行日志同步，而不是等每次heartbeat才进行一次同步，所以不存在不通过`SpeedTest`性能要求的问题。
作者使用每个`peer`一个协程，或者其他pipeline的做法，性能会更好。

**Comment by endless-hu** [comment]
> 可以看博主lab2中复制模型的描述。如果简单实现(不考虑资源浪费)的话，每次上次服务调用Start()时leader都会向peers发送sendAppendEntries()进行日志同步，而不是等每次heartbeat才进行一次同步，所以不存在不通过`SpeedTest`性能要求的问题。
> 作者使用每个`peer`一个协程，或者其他pipeline的做法，性能会更好。

万分感谢！
