### ISSUE TITLE
关于Lab2中末尾提到的liveness的问题

### ISSUE THREAD

**Issue by goldwind-ting** [LebronAl/MIT6.824-2021#24]
Lab2的末尾提到，用leader上任后提交一条空日志的方式解决所描述的corner case，但是空日志同样没法保证被复制到 majority followers，这样commitIndex还是1，客户端还是能读到旧的数据，貌似这种方法并不能解决这个问题，不知道我理解的对不对，还望赐教。

**Comment by OneSizeFitsQuorum** [comment]
目前 6.824 的 lab 里面是把读当做普通日志来处理的。对于新 leader 上任后发起的读请求，一旦走到 apply 那一步则至少已经已经提交了当前 term 的一条日志，因而不存在 safety 的问题
