### ISSUE TITLE
关于lab2D的疑问

### ISSUE THREAD

**Issue by EagleEyeKestrel** [LebronAl/MIT6.824-2021#26]
您好，想请教一个关于applier和InstallSnapshot（下文简称is）的同步问题。

首先看了测试代码（config.go/line 212, applierSnap函数），我的理解是，applier里发送给channel的命令会直接apply，检查index；而is会先调condis判断是否有lastIncludedIndex > rf.commitIndex，再决定是否apply这个snapshot。

设想如下情况：
某个follower此时lastApplied = 13, commitIndex = 18。 applier中切好了log entries，然后释放锁，开始遍历发送给channel。
比如发完15之后，leader发来lastIncludedIndex=19的snapshot。is，condis检查19>18，于是apply了这个snapshot。之后lastApplied = 19, commitIndex = 19。那is结束之后，applier里继续apply entry 16，由于不是snapshot，所以会直接应用，并检查下标是否是lastapplied + 1。那不是会error吗？

想问一下您的代码是如何避免这个情形的，没太想明白我对您的代码哪里理解有误。感谢！

**Comment by EagleEyeKestrel** [comment]
破案了，原来2021的lab的config.go的applierSnap里，在channel中只会apply > lastApplied的日志。
但我还是觉得您在applier里写的 确保每个日志apply exactly once是不是有点问题..

**Comment by OneSizeFitsQuorum** [comment]
你说的这个 case 我不是在[文档](https://github.com/OneSizeFitsQuorum/MIT6.824-2021/blob/master/docs/lab2.md#%E5%BC%82%E6%AD%A5-applier-%E7%9A%84-exactly-once)里面已经写了吗...和 snapshot 并发的时候需要在 KV 上层维护一下 index，不能直接 apply

**Comment by EagleEyeKestrel** [comment]
好的谢谢

**Comment by yinghuo302** [comment]
但在Lab2D中会检测applychan中的index是否正确，还是上面的情况，在Lab2D中会直接报错apply error: server 0 apply out of order, expected index 20, got 16，这个问题怎么解决
