### ISSUE TITLE
LAB2实现中可能存在的活锁

### ISSUE THREAD

**Issue by CharlieLei** [LebronAl/MIT6.824-2021#27]
```go
func (rf *Raft) RequestVote(request *RequestVoteRequest, response *RequestVoteResponse) {
	rf.mu.Lock()
	defer rf.mu.Unlock()
	defer rf.persist()
	defer DPrintf("{Node %v}'s state is {state %v,term %v,commitIndex %v,lastApplied %v,firstLog %v,lastLog %v} before processing requestVoteRequest %v and reply requestVoteResponse %v", rf.me, rf.state, rf.currentTerm, rf.commitIndex, rf.lastApplied, rf.getFirstLog(), rf.getLastLog(), request, response)

	if request.Term < rf.currentTerm || (request.Term == rf.currentTerm && rf.votedFor != -1 && rf.votedFor != request.CandidateId) {
		response.Term, response.VoteGranted = rf.currentTerm, false
		return
	}
	if request.Term > rf.currentTerm {
		rf.ChangeState(StateFollower)
		rf.currentTerm, rf.votedFor = request.Term, -1
	}
	if !rf.isLogUpToDate(request.LastLogTerm, request.LastLogIndex) {
		response.Term, response.VoteGranted = rf.currentTerm, false
		return
	}
	rf.votedFor = request.CandidateId
	rf.electionTimer.Reset(RandomizedElectionTimeout())
	response.Term, response.VoteGranted = rf.currentTerm, true
}
```
在选主的handler中，有可能出现：当前节点的Term比Candidate小，且原先是Leader，且自身的日志是upToDate的，但candidate的日志不是up-to-date。这样的话，该节点就会经过这一段代码：
```go
	if request.Term > rf.currentTerm {
		rf.ChangeState(StateFollower)
		rf.currentTerm, rf.votedFor = request.Term, -1
	}
	if !rf.isLogUpToDate(request.LastLogTerm, request.LastLogIndex) {
		response.Term, response.VoteGranted = rf.currentTerm, false
		return
	}
```
从而使得该节点的electionTimer没有被reset，从而不能成为Candidate。

有可能网络中出现这样的情况：
五个节点，出现了三个网络划分：L | L | L F F
1. 此时第3个划分中heartbeat传输很慢，但在等待返回的时候第3个Leader还在不断收到entry
2. 不久后第3个划分中某个Follower超时，成为Candidate
3. 与此同时，网络不再划分，5个节点都能收到该Candidate的requestVoteRPC
4. 此时该Candidate的term是所有节点中最大的，但与前三个原Leader节点相比，该Candidate的日志不是up-to-date的，因为：
    - Candidate日志的最后一项是在term很小的时候加入的，而前两个原Leader节点日志的最后一项有更大的term
    - Candidate日志最后一项和第三个原Leader节点日志的最后一项相同，但由于2.，原Leader节点的日志更长
5. 这导致前三个原Leader节点走上面的路径，没有reset自己的electionTimer，从而让选举只有后两个能成为Candidate，从而让所有能成为Leader的节点无法成为Candidate，从而无法选出Leader

不知道是否遇到这样的情况？若有的话请问是如何解决的呢？

**Comment by OneSizeFitsQuorum** [comment]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/32640567/212873945-bfa4e7c3-e71a-4bc7-b1fd-5dae88771bd1.png">
ChangeState 的源码里面有 reset 的逻辑，只不过文档里面没写。。。
