### ISSUE TITLE
请问Lab2B的tester是怎么检查committed的log的

### ISSUE THREAD

**Issue by UnbearableFate** [LebronAl/MIT6.824-2021#30]
测试Test 2的TestBasicAgree2B遇到的问题，  
我打印三个peers的log列表发现已经是同步的  
<img width="467" alt="截屏2023-05-18 18 09 00" src="https://github.com/OneSizeFitsQuorum/MIT6.824-2021/assets/6197181/3c06adfb-9291-4f95-94e2-697555948940">
但是tester总是不认为我已经提交了log，  
查看config.logs 描述的是  
`logs        []map[int]interface{} // copy of each server's committed entries`
但是也看遍了代码也看不出来是怎么复制我的raft中的log的。
请问这个测试器是怎么检查raft里的logs的呢

**Comment by OneSizeFitsQuorum** [comment]
好像是根据你 apply 日志的 index？
