### ISSUE TITLE
你好，可以发一份源码给我吗？我想参考一下一些具体实现细节！谢谢！

### ISSUE THREAD

**Issue by jiong1998** [LebronAl/MIT6.824-2021#31]
这是我的邮箱：29672599@qq.com

**Comment by OneSizeFitsQuorum** [comment]
不好意思回复的有点晚，已发送~

**Comment by OneSizeFitsQuorum** [comment]
<img width="1225" alt="image" src="https://github.com/OneSizeFitsQuorum/MIT6.824-2021/assets/32640567/9fc91415-fbd3-4f6b-bdb9-58b489112d8b">
邮件地址好像不对
