### ISSUE TITLE
即使代码正确，Lab2B的前几个 Task 是不是也有极小概率 Fail ?

### ISSUE THREAD

**Issue by KKKZOZ** [LebronAl/MIT6.824-2021#35]
我注意到，比如：
+ TestBasicAgree2B
+ TestFollowerFailure2B
+ TestLeaderFailure2B
这三个任务中的 `cfg.one()` 方法的最后一个参数是 `retry=false`，这就意味着，只会调用 `rf.Start()` 一次，有可能出现接收该请求的 Leader 还未提交日志就成为了 Follower，然后由于 `retry=false`，所以不会有新的请求进来（不会有新的 `rf.Start()` 的调用），这个 log 就一直提交不了（旧任期的 Log 不能被新任期的 Leader 提交），然后 2 秒后超时，导致测试失败，并提示"one(%v) failed to reach agreement"

因为 Lab2 是没有让实现 "no-op" 机制的，所以只要遇见这种情况，测试就会失败？

**Comment by KKKZOZ** [comment]
比如在 `TestBasicAgree2B` 中：

![image-20230921014812236](https://kkkzoz-1304409899.cos.ap-chengdu.myqcloud.com/img/image-20230921014812236.png)

**Comment by KKKZOZ** [comment]
比如在 TestBasicAgree2B 中：

图片地址：
https://kkkzoz-1304409899.cos.ap-chengdu.myqcloud.com/img/image-20230921014812236.png

**Comment by OneSizeFitsQuorum** [comment]
我印象中 21 年的 lab2 是不会去测 no-op 机制的，还是持续会有写入进来的，只不过可能换了个 Leader 去写入了（可以检查一些同步的逻辑看有没有问题）。lab4 需要去做 no-op 日志的处理

**Comment by KKKZOZ** [comment]
La2B 中确实有不会 retry 的测试点，如果发生了我所说的那个问题，确实会失败。

测试的编写人员假设了网络环境是理想的，却猜不到有同学在本地跑的时候负载过大发生长时间 GC 而导致测试失败的情况。

具体的分析在[这里](https://blog.kkkzoz.top/posts/talks/6.824-lab2b-research/)

**Comment by cyrilwongmy** [comment]
感谢KKKZOZ的分析! 我也遇到了这个问题, 所有报错的问题都是一样的 不实现no-op就会报错.
