### ISSUE TITLE
代码请求

### ISSUE THREAD

**Issue by Shane953** [LebronAl/MIT6.824-2021#39]
你好，发现你写的代码非常简洁明了， 能否发一份源码学习一下，改进一下我的实现思路
这是我的邮箱1205257902@qq.com，谢谢~

**Comment by MeWannaSleep** [comment]
加一[1539046044@qq.com](mailto:1539046044@qq.com)，谢谢~

**Comment by OneSizeFitsQuorum** [comment]
已发送~
