### ISSUE TITLE
请问你用 timer 的时候，一定是等到 timer expired 后再 reset 的吗

### ISSUE THREAD

**Issue by Smith-Cruise** [LebronAl/MIT6.824-2021#4]
我看官网那里说使用 timer reset 时，最好确保 timer expired 后再使用，我现在有莫名其妙的 bug，有些时候跑1000次都不一定出的来，感觉问题就是在计时器这里。

**Comment by OneSizeFitsQuorum** [comment]
不好意思，我测得次数总共加起来有上千次，但没有遇到 timer 相关的 bug。简单查了一下资料，似乎 timer.reset 确定有很多坑，不过个人感觉深挖 go 的 timer 实现已经和 6.824 没什么关系了，如果实在怀疑建议换一种定时方式就行。
