### ISSUE TITLE
AppendEntries和handleAppendEntriesResponse中，response.Term=0的情况

### ISSUE THREAD

**Issue by ohnoohmygod** [LebronAl/MIT6.824-2021#47]
![image](https://github.com/OneSizeFitsQuorum/MIT6.824-2021/assets/59137241/a06d72f1-fa8f-4ade-914a-1b21a87c4beb)
在AppendEntries中，为什么需要判断request.PrevLogIndex < rf.getFirstLog().Index？能否给一个场景说明一下。
而且在handle里并没有处理response.Term=0的情况。
感谢。

**Comment by OneSizeFitsQuorum** [comment]
一般会出现在 RPC 乱序时，这个时候不需要进行什么处理~
