### ISSUE TITLE
请问你是怎么解决某一个节点日志非常落后，然后要耗费大量时间同步的问题

### ISSUE THREAD

**Issue by Smith-Cruise** [LebronAl/MIT6.824-2021#5]
我自己在实现 raft accelerate backtrack 时，能够快速的找到 conflict index， appendEntry 发送时是直接批量发送属于这个term所有的entries，但是仍然会导致超时（同步的不够快），failed to reach agreement，
请问你是怎么处理的这块
或者你直接发下你的源码，我看下你是怎么处理的

**Comment by OneSizeFitsQuorum** [comment]
我做了 batching 的优化，所以同步起来可能快一点。可以关注下这里的[文档](https://github.com/LebronAl/MIT6.824-2021/blob/master/docs/lab2.md#%E5%A4%8D%E5%88%B6%E6%A8%A1%E5%9E%8B)。

**Comment by Smith-Cruise** [comment]
我看了你的 RequestVote 的代码，感觉里面是不是可能存在一种 bug。
假设 0 为 Leader，然后1，2暂时收不到Leader的heartbeat，然后开始选举。此时0，1连通，2断开，然后0收到了更大term的requestVote，变为follower了，但是因为 leader 的log是 up-to-date 的，不会投票给1或2，但是你的代码里面在这种情况下没有 reset timer，使得0不会自己进行选举。然后1也永远赢不了，就GG了

**Comment by OneSizeFitsQuorum** [comment]
0 在收到更大 term 的 requestVote RPC 时会更新自己的 term 和 voteFor，然后会调用 ChangeState(StateFollower)，这个函数里面会 reset 对应的 timer，所以我觉得应该不会有你说的这种现象出现。你再确认一下代码看看?

**Comment by Smith-Cruise** [comment]
额，好吧，我以为你 ChangeState 里面没有 reset timer，因为我看你每一步即使 ChangeState 后也 reset timer。主要你 ChangeState 里面的代码实现也没放出来呀，强烈希望一份源码，参考学习。

**Comment by OneSizeFitsQuorum** [comment]
加微信私发你吧~之后可以多交流hh，GitHub 上就不开源了

**Comment by Smith-Cruise** [comment]
ok 微信号发你 github 上面的邮箱了
