### ISSUE TITLE
关于日志复制的一点问题

### ISSUE THREAD

**Issue by Amadeus-1048** [LebronAl/MIT6.824-2021#50]
在论文中有提到，对于一个leader，If AppendEntries fails because of log inconsistency: decrement nextIndex and retry (§5.3)。
在作者的笔记和代码中，handleAppendEntriesResponse是领导者处理日志复制响应的方法，这个方法在遇到日志不一致的情况时，作者你对rf.nextIndex[peer]做了递减的操作，但是没有直接在这个方法里retry。
所以是由之后的ticker触发heartbeat时再重新尝试AppendEntries吗？ 这样处理和论文中提到的在AppendEntries fails之后直接 retry 有什么不同和影响吗？
感谢作者！希望能得到解答！

**Comment by OneSizeFitsQuorum** [comment]
> 所以是由之后的ticker触发heartbeat时再重新尝试AppendEntries吗？ 这样处理和论文中提到的在AppendEntries fails之后直接 retry 有什么不同和影响吗？

正确性上没什么区别，跟性能相关了。目前我在示例里面写的定期心跳 + 复制线程持续同步的方式是大多数生产级别 Raft 库的实现方案，在 response 里面触发进一步的同步在线程模型上会比较奇怪
