### ISSUE TITLE
求源码

### ISSUE THREAD

**Issue by shanzhiq** [LebronAl/MIT6.824-2021#54]
大佬可以发份源码参考下吗，邮箱shanzq233@gmail.com

**Comment by gexincoding** [comment]
大佬可以发份源码参考下吗，邮箱gexincoding@gmail.com

**Comment by OneSizeFitsQuorum** [comment]
已发送

**Comment by gexincoding** [comment]
邮箱貌似还没收到，能辛苦大佬再发一遍嘛？

Potato ***@***.***> 于2024年2月29日周四 17:42写道：

**Comment by PhiFever** [comment]
大佬求一份源码，谢谢！邮箱：hunterludwig117@gmail.com

**Comment by OneSizeFitsQuorum** [comment]
gexincoding ***@***.***> 于2024年2月29日周四 17:55写道：

**Comment by geoffelis** [comment]
大佬求一份源码！谢谢！邮箱：projectygclub@gmail.com

**Comment by Leu552** [comment]
大佬求一份源码参考下！！感谢 有些jiac_liu@163.com

**Comment by soulrrrrr** [comment]
大佬求一份源码！谢谢！邮箱 chialun100@gmail.com

**Comment by 2498298782Zql** [comment]
大佬求源码！快被这个搞奔溃了2498298782@qq.com
