### ISSUE TITLE
Lab2 的日志复制线程模型可能会导致 2D Test 超时

### ISSUE THREAD

**Issue by lhzds** [LebronAl/MIT6.824-2021#55]
测试的网络设置默认 `cfg.net.LongDelays(true)`，这个会导致发起的 RPC 里走到一处 `ms = (rand.Int() % 7000)`，使得给 disconnect 的机器发 RPC 最高耗时 7s、平均耗时 3.5 s 才返回失败。
在 2D的测试，会在机器disconnect又重新connect条件下进行30轮的日志同步，测试限制120s。每个协程单独分配一个协程持续进行日志复制的话，每轮在给 disconnect 的机器发 AppendEntries Rpc 时平均大概阻塞3.5s再进行重试。如果其他部分优化不好、随机的延迟比较大，或者测试机器性能差一点，很容易就是导致测试超时（超过120s）。
设置 `cfg.net.LongDelays(false)`，或者定时创建协程发送 AppendEnries Rpc 的话就可以解决这个问题。

**Comment by OneSizeFitsQuorum** [comment]
也许新增的一些测试用例会导致该问题，要是改回有效的话也可以不搞这个优化。这个优化在 etcd/ratis 等工程项目代码实现里面都是这么做的，可以作为一个参考思路~
