### ISSUE TITLE
follower 拒绝过期 SnapShot 导致 follower 日志过长

### ISSUE THREAD

**Issue by gexincoding** [LebronAl/MIT6.824-2021#57]
请教一下，如果这么做的话，会不会导致 leader 已经压缩了，但是follower的日志长度过长，leader没有感知到
![image](https://github.com/OneSizeFitsQuorum/MIT6.824-2021/assets/98001140/2c43626c-57bd-4205-bd3a-4f4da05e27e2)

**Comment by OneSizeFitsQuorum** [comment]
Leader 和 Follower 都会独自定期 snapshot 的，所以不存在 Follower 拒绝 Leader Snapshot 而导致日志过长的问题

**Comment by gexincoding** [comment]
万分感谢


Potato ***@***.***> 于2024年3月12日周二 15:01写道：
