### ISSUE TITLE
大佬，请问lab4b中一个raft节点就有一个shardkv吗？比如一个group组，下面有一个raft集群，共有5个raft节点，则共有5个shardkv，但是只有一个leader节点的shardkv对外提供服务吗？

### ISSUE THREAD

**Issue by 2498298782Zql** [LebronAl/MIT6.824-2021#59]
大佬，请问lab4b中一个raft节点就有一个shardkv吗？比如一个group组，下面有一个raft集群，共有5个raft节点，则共有5个shardkv，但是只有一个leader节点的shardkv对外提供服务吗？

**Comment by 2498298782Zql** [comment]
如果是一个raft集群对应一个shardkv，那如何解释在shardkv的client的command方法是遍历一个group下的所有server节点呢？

**Comment by OneSizeFitsQuorum** [comment]
应该是先根据 key 找到对应的 shard，其对应一个 group，然后再去这个 group 中遍历找 leader 读写？

**Comment by 2498298782Zql** [comment]
那假设leader节点挂掉了，新的leader节点如何有就leader节点的shardkv数据
