### ISSUE TITLE
请教一下关于 leader 选举的问题

### ISSUE THREAD

**Issue by Amadeus-1048** [LebronAl/MIT6.824-2021#60]
我看选举规则有提到：日志完整性高的跟随者拒绝投票给日志完整性低的候选人。
也看到有人举了例子：
当leader选举中，B节点的任期编号为1，日志编号为2。A节点任期编号为2，日志编号为1。
B节点收到A节点的请求投票消息，B会投票给A节点吗？
不会，B节点的编号大于A节点，说明B节点的日志完整度更高，更适合当选leader。

但是作者您的代码中 isLogUpToDate 方法好像没有实现这个逻辑？

**Comment by waterm310n** [comment]
以我的理解，在你所举的例子中B当前的任期是1，状态时Follower或者Leader，它的log如下
`LogIndex:0 Cmd:Nil Term:0|LogIndex:1 Cmd:any Term:1|LogIndex:2 Cmd:any Term:1`
A当前的任期是2，状态是Candidate，它的log如下
`LogIndex:0 Cmd:Nil Term:0|LogIndex:1 Cmd:any Term:1|`
你的意思是有可能存在另一个C它与B是相同的日志，然后因为符合大多数原则，所以C与B应用了LogIndex1,2，所以此时如果同意A的投票请求，就会出错。
作者的`isLogUpToDate`方法接受了两个参数`LastLogIndex`与`LastLogTerm`，应该就足够实现这个逻辑了吧？
B可以检查完`Term`后，拿自己的`LastLogIndex`与A的`LastLogIndex`相比，发现比A的大，`isLogUpDate`就可以返回false了吧？

**Comment by Amadeus-1048** [comment]
> 以我的理解，在你所举的例子中B当前的任期是1，状态时Follower或者Leader，它的log如下 `LogIndex:0 Cmd:Nil Term:0|LogIndex:1 Cmd:any Term:1|LogIndex:2 Cmd:any Term:1` A当前的任期是2，状态是Candidate，它的log如下 `LogIndex:0 Cmd:Nil Term:0|LogIndex:1 Cmd:any Term:1|` 你的意思是有可能存在另一个C它与B是相同的日志，然后因为符合大多数原则，所以C与B应用了LogIndex1,2，所以此时如果同意A的投票请求，就会出错。 作者的`isLogUpToDate`方法接受了两个参数`LastLogIndex`与`LastLogTerm`，应该就足够实现这个逻辑了吧？ B可以检查完`Term`后，拿自己的`LastLogIndex`与A的`LastLogIndex`相比，发现比A的大，`isLogUpDate`就可以返回false了吧？

是的，我的理解有误，A节点的任期大不代表其日志的任期也更大，感谢解答。
