### ISSUE TITLE
请问选举和心跳计时器的时间应该设置为多少？

### ISSUE THREAD

**Issue by ziannchen** [LebronAl/MIT6.824-2021#7]
我在一直无法通过ab3的TestSpeed3A测试，他提示我test_test.go:413: Operations completed too slowly 61.653846ms/op > 33.333333ms/op，完成每次operation的用时太长了。我看了日志，从调用Start（）到raft层apply的用时一开始是几毫秒到了后期增加到几百毫秒。我觉得可能有计时器时间设置的问题，可以为我提供一些建议吗？

**Comment by OneSizeFitsQuorum** [comment]
我应该设置的是 1s 和 125ms。可以 profile 一下 apply 为何会慢？也可能是不是在 apply 的时候做了 persist（实际并不需要），所以才越来越慢？

**Comment by ziannchen** [comment]
我今天重新读了几遍代码，确实是persist的使用上有些问题。有的RPC在返回前调用了多次persist，改为只调用一次，这样之后每次operation用时降到了30秒以内。但是该次测试（TestSpeed3A）用时始终为30s左右，几乎是官方的两倍。
