### ISSUE TITLE
感谢大佬的lab分享，但想求一份源码，有几个地方不是很明白

### ISSUE THREAD

**Issue by tko81** [LebronAl/MIT6.824-2021#76]
guojin96542008@gmail.com

**Comment by ddd-ms** [comment]
好兄弟你拿到了吗，我也想要，能不能给我也发一份dddms172@gmail.com

**Comment by ddd-ms** [comment]
> [guojin96542008@gmail.com](mailto:guojin96542008@gmail.com)

好兄弟你拿到了么，我也想要，能不能给我也发一份dddms172@gmail.com

**Comment by OneSizeFitsQuorum** [comment]
已发送

**Comment by ddd-ms** [comment]
> 已发送

感谢！

**Comment by ddd-ms** [comment]
> 已发送
大佬我好像没有收到欸，能不能再发一份呢，要不换个邮箱？2541684445@qq.com

**Comment by OneSizeFitsQuorum** [comment]
@ddd-ms 已发

**Comment by ddd-ms** [comment]
> @ddd-ms 已发

much appreciated!

**Comment by CHYhave** [comment]
同求 949687815@qq.com

**Comment by summeriiii** [comment]
@OneSizeFitsQuorum  大佬，求一份代码 2876645134@qq.com, 感谢

**Comment by seriouslym** [comment]
@OneSizeFitsQuorum 大佬，同求一份代码 769582861@qq.com 十分感谢
