### ISSUE TITLE
关于lab3中kvservice层持久化状态的一些疑问

### ISSUE THREAD

**Issue by ziannchen** [LebronAl/MIT6.824-2021#8]
我的实现是在kv层的applier中每从applych中读出一个applymsg，判断下raftstatesize是否达到阈值，若达到则为kv层打快照并下发给raft层。除此之外是否还需要在什么时候持久化kv层的状态，就类似raft层中持久化term、log等状态一样。因为我遇到了一个问题 test_test.go:144: duplicate element x 0 31 y in Append result。 我查看了日志发现是每个kvserver都已将同一条append RPC应用于状态机并更新了session map，这里没有打快照，然后在回复clerk之前被测试程序kill了。

**Comment by OneSizeFitsQuorum** [comment]
我做 snapshot 的逻辑也是这样。实际上本质来说，持久性是由 lab2 的 raft 保证的。snapshot 只是做了一个压缩，其应该保证原子性，即做 snapshot 前后都不影响节点的恢复的。PS：没看懂你的问题是什么？

**Comment by ziannchen** [comment]
不好意思issue没有写完整  我的问题：是在状态机和session map更新之后，回复clerk之前，此时没有打快照且kvserver被测试程序kill了。然后kvserver重启之后是从之前保存的快照中恢复session map，所以这里kv层丢失了一次处理了append RPC的记录。由于kvserver被kill前没有回复clerk，所以clerk会重试相同的append RPC，造成了状态机被重复append的情况。我想知道的是：除了raftstatesize达到阈值之后的快照之外，是否还需要额外的持久化kv层信息的操作。

**Comment by OneSizeFitsQuorum** [comment]
你说的这种情况和 kv 层持久化没关系，应该是 raft 层应该保证的可恢复性。kv 层从 applyCh 里面获取的日志肯定是已经 commit 的，raft 层应该保证即使被 kill 了重启后，其也能够被恢复并重新 push 到 applyCh 里来让 kv 层的状态机恢复。所以建议你检查下 raft 层的持久化是不是哪里漏写了吧？

**Comment by ziannchen** [comment]
这下我理解了 感谢
