### ISSUE TITLE
关于Lab3A

### ISSUE THREAD

**Issue by Jay9625** [LebronAl/MIT6.824-2021#9]
你好，参考了你的设计遇到了这样一个问题：
node0为主结点，接收到{clientId: 1, seqNum: 1, op:Get}，并将该命令用Start发到raft层，得到CommandIndex: 1。接下来kv.Command 函数创建了notifyChan1，等待kv.applier发送response。

此时raft的node0挂掉，随后又被选举为主结点。这个过程中，kv.Command超时，导致RPC返回了ErrTimeout。（这个时候notifyChan1没有收到response，是否以后再也无法收到？）

node0恢复为主结点后，raft.applier发送applyMsg到kv.applier，然后kv.applier发送response到notifyChan1，但是由于kv.Command早就超时返回，notifyChan1不会接收response。此时，kv.applier阻塞。

客户端重发RPC，kv.Command，但是因为kv.applier的堵塞，并且它还持有kv.mu.lock，所以kv.Command也阻塞。死锁。

请问我哪里理解错误了？

**Comment by OneSizeFitsQuorum** [comment]
> node0恢复为主结点后，raft.applier发送applyMsg到kv.applier，然后kv.applier发送response到notifyChan1，但是由于kv.Command早就超时返回，notifyChan1不会接收response。此时，kv.applier阻塞。

这里为什么会阻塞呢？在我的实现中，首先 chan 是带缓冲的，不应该阻塞 applier 协程；其次只有 apply 当前 term 的日志才会去尝试往 chan 里面 push 进而通知客户端，因为之前 term 的日志去通知也没有意义。检查一下这里吧

**Comment by Jay9625** [comment]
> 其次只有 apply 当前 term 的日志才会去尝试往 chan 里面 push 进而通知客户端，因为之前 term 的日志去通知也没有意义。检查一下这里吧

你这里考虑的是applyChan传递期间raft层可能发生变故。是吧？我遇到的错误应该不是这个问题。
我的问题中，由于超时，对于同一个读RPC产生了两个notifyChan（raft层已经有两个相同的命令，但是都还未apply），raft恢复后，先对前一个进行了应用，引起kv.applier向一个旧的notifyChan发送了消息。但是因为旧的通道不再接收，就导致了kv.applier的阻塞。（我没有用带缓冲的通道，这里产生了死锁，按理说应该会报错，但程序却只是一直阻塞）
```
	select {
	case result := <-ch:
		response.Value, response.Err = result.Value, result.Err
	case <-time.After(ExecuteTimeout):
		response.Err = ErrTimeout
	}
```
所以，我想知道对于这样的*过期*的notifyChan我是不是应该拒绝发送，可是您的代码逻辑中好像并没有处理？

感谢回复。

**Comment by OneSizeFitsQuorum** [comment]
1. 我的代码中只会对当前 term 的日志往 chan 里 push，如果 node0 本来是主节点，挂掉重启后又当选了 leader，这个时候 term 显然已经增大了，那么 apply 的时候就不会再去 push chan 了。
2.不带缓冲的 chan 没有 receiver 的话 applier 协程肯定会阻塞的吧，这个没什么好说的

**Comment by Jay9625** [comment]
> 如果 node0 本来是主节点，挂掉重启后又当选了 leader，这个时候 term 显然已经增大了

我的问题，我raft的applyMsg用的是rf.currentTerm，导致筛选过期信息的逻辑失效了。
我一直觉得这个log有点奇怪，但是又没往这方面想，你这一说我突然想起来了。。。
再次表示感谢。

**Comment by OneSizeFitsQuorum** [comment]
没事，欢迎交流~
